default_stages:
  - commit
  - push
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        stages:
          - commit
  - repo: https://github.com/python/black
    rev: 23.1.0
    hooks:
      - id: black
        stages:
          - commit
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        stages:
          - commit
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ['--config=.flake8']
        stages:
          - commit
